### ISSUE TITLE
leaflet dates

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/loop-sensor-trends#174]
Noticed that Dec. 21-28 are currently options for date selections in the leaflet module...but there is no traffic data populating the map (although the data does appear to be in the scatterplot).

**Comment by eroten** [comment]
This should be fixed as of ec9233911e2327e3d81a2898ffdd82b3dff4d963. Will double check live app once it deploys

**Comment by eroten** [comment]
This seems to have resolved. 👍
