### ISSUE TITLE
Date selector- add capability for additional months

### ISSUE THREAD

**Issue by JonathanEhrlichMC** [Metropolitan-Council/loop-sensor-trends#18]
Right now the only data we care about  is in March, but we'll have April data next week. Will the date selector allow selection of another month once there is data, or is that something you need to program?

**Comment by eroten** [comment]
No additional programming! The options are based on the min/max dates of the dataset, so it will update as we update the dataset.

**Comment by JonathanEhrlichMC** [comment]
cool
