### ISSUE TITLE
consider adding COVID-19 developments

### ISSUE THREAD

**Issue by eroten** [Metropolitan-Council/loop-sensor-trends#20]
Sources like the [COVID Tracking Project](https://covidtracking.com/) and the [NY Times COVID tracking data](https://github.com/nytimes/covid-19-data) make it really easy for us to include daily updates. 

However, this information is going to be available from MDH, and may be outside the scope of this app.

**Comment by JonathanEhrlichMC** [comment]
I think we should leave it out for now.

**Comment by eroten** [comment]
I am closing this issue for now, but we can re-open it if needed
