### ISSUE TITLE
Scale on daily time-series plot changes when  you turn on/off the daily and 7-day trend data

### ISSUE THREAD

**Issue by JonathanEhrlichMC** [Metropolitan-Council/loop-sensor-trends#203]

**Comment by eroten** [comment]
@JonathanEhrlichMC could you provide a couple screenshots of this app behavior? I think I know what you're referring to, but I want to be sure

**Comment by JonathanEhrlichMC** [comment]
![1](https://user-images.githubusercontent.com/46330806/128543254-70fecac0-9893-4809-aa7d-739e95a17151.JPG)
![2](https://user-images.githubusercontent.com/46330806/128543256-aa089802-ea88-4ac6-bc8f-6de3b4f71edf.JPG)

I hope this is helpful- it's hard to see in a screenshot. Toggle between the 4 states of the two buttons and it is clearer.

**Comment by eroten** [comment]
Oh! I see its the x-axis scale that is changing. Good catch.

The reason is that there isn't a rolling average for the first few days of the dataset (December 31, 2019 - January 2, 2020). I will set the x and y axis ranges manually so they won't auto-update.

**Comment by JonathanEhrlichMC** [comment]
Make sure not to fix the max x-axis range to a constant value, as that will change with every data update
