### ISSUE TITLE
separate out WIM counters from loop sensor counters

### ISSUE THREAD

**Issue by ashleyasmus** [Metropolitan-Council/loop-sensor-trends#24]
this leads to some really big volumes (huge nodes on the map)

**Comment by ashleyasmus** [comment]
(maybe this matters less if we make all nodes the same size)

**Comment by eroten** [comment]
slightly unrelated, but would it be interesting to show the vehicle weight distribution over time for the WIMs?

**Comment by JonathanEhrlichMC** [comment]
Why do WIMs count higher volumes?

**Comment by ashleyasmus** [comment]
there are some nodes with both wim counters and loop detectors. this leads to double-counting.
