### ISSUE TITLE
show hourly data

### ISSUE THREAD

**Issue by ashleyasmus** [Metropolitan-Council/loop-sensor-trends#25]
- ashley needs to qa/qc the hourly models
- ashley needs to figure out how to visualize this in a plot and map
- at node level? at region level? at corridor level?

**Comment by JonathanEhrlichMC** [comment]
I showed the hourly plots to Nick and Amy this morning. They thought it was definitely worth showing. Not sure the best way to visualize.

**Comment by eroten** [comment]
Now considered a duplicate of #187
