### ISSUE TITLE
Name spelling/agencies

### ISSUE THREAD

**Issue by JonathanEhrlichMC** [Metropolitan-Council/loop-sensor-trends#6]
Spell Jonathan Ehrlich correctly :|
Brian Kary is with MnDOT

**Comment by JonathanEhrlichMC** [comment]
And MnDOT is always MnDOT, never MNDOT (under Data sources)

**Comment by JonathanEhrlichMC** [comment]
Also Sara Maaske is misspelled. Is there a reason why you don't want her email address live?

**Comment by eroten** [comment]
🤖s can scrape live email addresses more easily
