### ISSUE TITLE
Graph labels- rounding etc

### ISSUE THREAD

**Issue by JonathanEhrlichMC** [Metropolitan-Council/loop-sensor-trends#7]
Tooltip- round to nearest tenth of a percent.

For the dates- Is it to busy to put day of week? or to indicate Sundays with the vertical gray lines rather than every three days?

**Comment by eroten** [comment]
Where did you see the rounding not be to the nearest 10th?

**Comment by JonathanEhrlichMC** [comment]
Tool tips in graph are rounding to the hundredth of a percent

**Comment by eroten** [comment]
okay so without day names
![image](https://user-images.githubusercontent.com/16826194/77942107-cda8e600-7280-11ea-8c9b-1cfba005bc76.png)

And with full day names 
![image](https://user-images.githubusercontent.com/16826194/77942348-182a6280-7281-11ea-8035-3d58c7bcf164.png)

The full names look fine to me, @JonathanEhrlichMC

**Comment by JonathanEhrlichMC** [comment]
Full names look fine to me too now. They might not as the x-axis gets longer over time. Abbreviate Sunday to Sun. ?
